/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'custom-icons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'customlogo-text': '&#xe901;',
		'customlogo-simple': '&#xe902;',
		'customlogo-silhouette': '&#xe903;',
		'customlogo': '&#xe904;',
		'customhome': '&#xe900;',
		'custompencil': '&#xe905;',
		'customeyedropper': '&#xe90a;',
		'customdroplet': '&#xe90b;',
		'customimages': '&#xe90e;',
		'customcamera': '&#xe90f;',
		'customheadphones': '&#xe910;',
		'customplay': '&#xe912;',
		'customfilm': '&#xe913;',
		'custompacman': '&#xe916;',
		'custombullhorn': '&#xe91a;',
		'customconnection': '&#xe91b;',
		'custommic': '&#xe91e;',
		'custombooks': '&#xe920;',
		'customfile-text': '&#xe922;',
		'customfiles-empty': '&#xe925;',
		'customfile-picture': '&#xe927;',
		'customfile-play': '&#xe929;',
		'customstack': '&#xe92e;',
		'customfolder-open': '&#xe930;',
		'customprice-tag': '&#xe935;',
		'customcart': '&#xe93a;',
		'customphone': '&#xe942;',
		'customaddress-book': '&#xe944;',
		'custompushpin': '&#xe946;',
		'customlocation': '&#xe947;',
		'customcompass': '&#xe949;',
		'customclock': '&#xe94e;',
		'customclock2': '&#xe94f;',
		'customprinter': '&#xe954;',
		'customkeyboard': '&#xe955;',
		'customdisplay': '&#xe956;',
		'custommobile': '&#xe958;',
		'customtablet': '&#xe95a;',
		'customundo2': '&#xe967;',
		'customredo2': '&#xe968;',
		'customforward': '&#xe969;',
		'customreply': '&#xe96a;',
		'custombubble': '&#xe96b;',
		'custombubbles2': '&#xe96d;',
		'custombubble2': '&#xe96e;',
		'custombubbles4': '&#xe970;',
		'customuser': '&#xe971;',
		'customuser-plus': '&#xe973;',
		'customuser-minus': '&#xe974;',
		'customuser-check': '&#xe975;',
		'customquotes-left': '&#xe977;',
		'customquotes-right': '&#xe978;',
		'customspinner': '&#xe97a;',
		'customspinner2': '&#xe97b;',
		'customspinner9': '&#xe982;',
		'customsearch': '&#xe986;',
		'customzoom-in': '&#xe987;',
		'customzoom-out': '&#xe988;',
		'customenlarge': '&#xe989;',
		'customshrink': '&#xe98a;',
		'customenlarge2': '&#xe98b;',
		'customshrink2': '&#xe98c;',
		'customlock': '&#xe98f;',
		'customunlocked': '&#xe990;',
		'customwrench': '&#xe991;',
		'customcog': '&#xe994;',
		'customcogs': '&#xe995;',
		'customgift': '&#xe99f;',
		'custombin': '&#xe9ac;',
		'custombin2': '&#xe9ad;',
		'customairplane': '&#xe9af;',
		'customtruck': '&#xe9b0;',
		'customtarget': '&#xe9b3;',
		'customswitch': '&#xe9b6;',
		'customlist': '&#xe9ba;',
		'custommenu': '&#xe9bd;',
		'customcloud': '&#xe9c1;',
		'customcloud-download': '&#xe9c2;',
		'customcloud-upload': '&#xe9c3;',
		'customcloud-check': '&#xe9c4;',
		'customlink': '&#xe9cb;',
		'customflag': '&#xe9cc;',
		'customeye': '&#xe9ce;',
		'customeye-blocked': '&#xe9d1;',
		'customstar-empty': '&#xe9d7;',
		'customstar-half': '&#xe9d8;',
		'customstar-full': '&#xe9d9;',
		'customheart': '&#xe9da;',
		'customwarning': '&#xea07;',
		'customnotification': '&#xea08;',
		'customquestion': '&#xea09;',
		'customplus': '&#xea0a;',
		'customminus': '&#xea0b;',
		'custominfo': '&#xea0c;',
		'customcancel-circle': '&#xea0d;',
		'customblocked': '&#xea0e;',
		'customcross': '&#xea0f;',
		'customcheckmark': '&#xea10;',
		'customplay2': '&#xea15;',
		'custompause': '&#xea16;',
		'customstop': '&#xea17;',
		'customplay3': '&#xea1c;',
		'custompause2': '&#xea1d;',
		'customstop2': '&#xea1e;',
		'customvolume-high': '&#xea26;',
		'customvolume-medium': '&#xea27;',
		'customvolume-low': '&#xea28;',
		'customvolume-mute': '&#xea29;',
		'customvolume-mute2': '&#xea2a;',
		'customcircle-up': '&#xea41;',
		'customcircle-right': '&#xea42;',
		'customcircle-down': '&#xea43;',
		'customcircle-left': '&#xea44;',
		'customcheckbox-checked': '&#xea52;',
		'customcheckbox-unchecked': '&#xea53;',
		'customradio-checked': '&#xea54;',
		'customradio-checked2': '&#xea55;',
		'customradio-unchecked': '&#xea56;',
		'customshare2': '&#xea82;',
		'customgoogle-plus': '&#xea88;',
		'customgoogle-plus2': '&#xea89;',
		'customgoogle-drive': '&#xea8b;',
		'customfacebook': '&#xea8c;',
		'customfacebook2': '&#xea8d;',
		'custominstagram': '&#xea90;',
		'customtwitter': '&#xea91;',
		'customtwitter2': '&#xea92;',
		'customfeed2': '&#xea94;',
		'customfeed3': '&#xea95;',
		'customyoutube': '&#xea97;',
		'customyoutube2': '&#xea98;',
		'customyoutube3': '&#xea99;',
		'customyoutube4': '&#xea9a;',
		'customvimeo': '&#xea9c;',
		'customvimeo2': '&#xea9d;',
		'customflickr2': '&#xeaa1;',
		'customflickr3': '&#xeaa2;',
		'custompicassa': '&#xeaa4;',
		'custompicassa2': '&#xeaa5;',
		'customdribbble': '&#xeaa6;',
		'customdribbble2': '&#xeaa7;',
		'customdeviantart': '&#xeaab;',
		'customdeviantart2': '&#xeaac;',
		'customdropbox': '&#xeaaf;',
		'customgithub': '&#xeab1;',
		'customgithub5': '&#xeab5;',
		'customtumblr': '&#xeabb;',
		'customtumblr2': '&#xeabc;',
		'customapple': '&#xeabf;',
		'customandroid': '&#xeac1;',
		'customwindows': '&#xeac2;',
		'customwindows8': '&#xeac3;',
		'customskype': '&#xeac6;',
		'customlinkedin': '&#xeac8;',
		'customlinkedin2': '&#xeac9;',
		'custompinterest': '&#xead0;',
		'custompinterest2': '&#xead1;',
		'customfoursquare': '&#xead5;',
		'custompaypal': '&#xead6;',
		'customfile-pdf': '&#xeada;',
		'customfile-word': '&#xeadc;',
		'customhtml5': '&#xeadf;',
		'customhtml52': '&#xeae0;',
		'customchrome': '&#xeae5;',
		'customfirefox': '&#xeae6;',
		'customIE': '&#xeae7;',
		'customopera': '&#xeae8;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/custom[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
